### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ersinesen** [yahoo/egads#17]
I cant compile the code (java 1.7, ubuntu 14.04) due to a generics error (unchecked call) that, I think, was only a warning in previous java versions.

Is there a way to resolve this issue?

**Comment by nlaptev** [comment]
Have you tried compiling with Java 1.8+ ?

**Comment by ersinesen** [comment]
I have not. I will try.

**Comment by ersinesen** [comment]
The same error holds for java 1.8.0_60 too.

**Comment by nlaptev** [comment]
What about mvn version? Using 
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 13:51:28+0000)
Java version: 1.8.0_25, vendor: Oracle Corporation 
and running mvn clean compile assembly:single compiles without a problem.

**Comment by wroeland** [comment]
I got the same errors as mr. ersinesen, following steps solved the problem,
probably only the last is needed ...

I tried the mr. nlaptev recommandation so mvn -version gives me now
>Apache Maven 3.0.5
>Maven home: /usr/share/maven
>Java version: 1.8.0_60, vendor: Oracle Corporation
>Java home: /usr/lib/jvm/java-8-oracle/jre
>Default locale: en_US, platform encoding: UTF-8
>OS name: "linux", version: "3.16.0-48-generic", arch: "amd64", family: "unix"

Still didn't solve my problem, next i deleted/changed following lines from pom.xml
> < plugin >
>            < groupId >org.apache.maven.plugins< /groupId >
>            < artifactId >maven-compiler-plugin< /artifactId >
>            < configuration >
>              < compilerVersion >1.7< /compilerVersion >
>              < source >1.7< /source >
>              < target >1.7< /target >
>            < /configuration >
> < /plugin >

Note I removed the following line :
> < compilerArgument >-Xlint:unchecked< /compilerArgument >

**Comment by nlaptev** [comment]
Thanks guys. I committed the new pom.xml based on your feedback. Let me know if the issue still exists.
