### ISSUE TITLE
Where is the Alerting Module?

### ISSUE THREAD

**Issue by quydoan** [yahoo/egads#27]
I saw that the paper https://labs.yahoo.com/_c/uploads/KDD2015.pdf has mentioned about three module: the time-series modeling module (TMM), the anomaly detection module (ADM) and the alerting module (AM).  But I only found TMM (com.yahoo.egads.models.tsmm) and ADM (com.yahoo.egads.models.adm) in the package. Where is the AM?

**Comment by kashif** [comment]
@quydoan i think the alerting module is part of their business logic and infrastructure use case so it makes no sense to have it here since everyone will have their own way of doing alerts

**Comment by quydoan** [comment]
@kashif: Yeah, It makes sense. I just wondered whether I missed it.
