### ISSUE TITLE
AdaptiveKernelDensityChangePointDetector.java cannot find symbol

### ISSUE THREAD

**Issue by beedotkiran** [yahoo/egads#32]
I have tried to simply compile the code (on ubuntu 14.04) but fail : 

Steps performed till now : 
1. git clone
2.  export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
3. mvn clean compile assembly:single

This yields the following error:

[INFO] Compilation failure
/home/kiran/toolbox/egads-yahoo-AD/egads/src/main/java/com/yahoo/egads/models/adm/AdaptiveKernelDensityChangePointDetector.java:[172,82] cannot find symbol
  symbol:   method join(java.lang.String,java.lang.String)
  location: class java.lang.String

I am not familiar with java code and do not understand what could be the problem.

**Comment by chrisbangun** [comment]
same here, I got the same error

**Comment by fherrador** [comment]
No way to compile ot as it is, same error guys...

**Comment by pse1202** [comment]
String.join is a method introduced in Java 1.8. Why don't you try updating your hdk to 1.8?

@beedotkiran @chrisbangun @fherrador

**Comment by manolama** [comment]
Looks like we'll be using JDK 8 features going forward. I fixed the POM so that it will warn you if you're not compiling under 8. 489c2bc64ffd8edf8ef44fd838ad19d151618766. Sorry for the trouble!
