### ISSUE TITLE
Error: Could not find or load main class com.yahoo.egads.Egads

### ISSUE THREAD

**Issue by adamzjk** [yahoo/egads#46]
i installed the latest version of java JDK and maven on win10, then i successfully compiled using command `mvn clean compile assembly:single`, but when i type this
`java -Dlog4j.configurationFile=src/test/resources/log4j2.xml -cp target/egads-*-jar-with-dependencies.jar com.yahoo.egads.Egads src/test/resources/sample_config.ini src/test/resources/sample_input.csv`
an error occurs:
**Error: Could not find or load main class com.yahoo.egads.Egads**

**Comment by sashaankadibhatla** [comment]
hey i am also encoutering same issue how to resolve?

**Comment by Karlrita** [comment]
specifying the jar file name solves my same issue, e.g.:

java -Dlog4j.configurationFile=src/test/resources/log4j2.xml -cp target/egads-0.4.0-jar-with-dependencies.jar com.yahoo.egads.Egads src/test/resources/sample_config.ini src/test/resources/sample_input.csv

**Comment by adamzjk** [comment]
@sashaankadibhatla the original commands from the doc only work on Linux, change the command line style to windows then it'll work
